services:
  letsencrypt:
    image: "jrcs/letsencrypt-nginx-proxy-companion:2.3"
    container_name: "letsencrypt-helper"
    volumes:
      - "html:/usr/share/nginx/html"
      - "dhparam:/etc/nginx/dhparam"
      - "vhost:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs"
      - "/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      NGINX_PROXY_CONTAINER: "reverse-proxy"
      DEFAULT_EMAIL: "rdcmdev@gmail.com"
    restart: "always"
    depends_on:
      - "reverse-proxy"
    networks: 
      - "containers-network"
  reverse-proxy:
    image: "jwilder/nginx-proxy:1.5-alpine"
    container_name: "reverse-proxy"
    volumes:
      - "html:/usr/share/nginx/html"
      - "dhparam:/etc/nginx/dhparam"
      - "vhost:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs"
      - "/run/docker.sock:/tmp/docker.sock:ro"
    restart: "always"
    networks: 
      - "containers-network"
    ports:
      - "80:80"
      - "443:443"
  website:
    restart: "always"
    build: ./
    environment:
      VIRTUAL_HOST: "rodrigocmoraes.site"
      LETSENCRYPT_HOST: "rodrigocmoraes.site"
    networks: 
      - "containers-network"
volumes:
  certs:
  html:
  vhost:
  dhparam:
networks:
  containers-network:
    external: true